### ISSUE TITLE
Failed to load BEAGLE library: no hmsbeagle32 in java.library.path

### ISSUE THREAD

**Issue by andreas-chrysostomou** [beagle-dev/beagle-lib#152]
I have downloaded beast on windows, downloaded beagle, restarted pc, tried to run an xml file and got this issue. I searched online and tried various solutions like copying the beagle files to where the executable is. nothing works. Please help

**Comment by rsippy** [comment]
I'm having the same problem. I've uninstalled and reinstalled everything, restarted the computer. Same error message when I try to check for Beagle from Beast. Help!

**Comment by zhongyan5058** [comment]
This (linux-based) error occurs because BEAST is unable to locate the BEAGLE library. When following the installation instructions and specifically the part on how to set the environment variables, BEAST should be able to locate BEAGLE without any additional instructions. Should setting the environment variables no take care of this issue, you can manually provide the location of BEAGLE when running BEAST as follows:
java -Djava.library.path=/usr/local/lib -jar beast.jar test.xml
in the case that you installed BEAGLE in /usr/local/lib. When following the installation instructions, BEAGLE will be installed in the /lib folder within your HOME directory. If you're unsure where you've installed BEAGLE, you can locate the BEAGLE library as follows:
locate libhmsbeagle-jni.so
On Windows, it may be necessary to restart your computer after installing BEAGLE, in order for the system's environment variables to be set up correctly. If that doesn't work, you can try copying the BEAGLE DLL files from C:\Program Files\Common Files:
hmsbeagle64.dll
hmsbeagle-cpu64.dll
hmsbeagle-opencl64.dll
to the same directory that holds you BEAST executable, e.g. BEASTv1.10.4.exe.
