### ISSUE TITLE
Not finding CUDA 7.5 resource

### ISSUE THREAD

**Issue by yunesj** [beagle-dev/beagle-lib#86]
I installed CUDA 7.5-18 according to http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#ubuntu-installation.

deviceQuery is reporting:
```
Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 970"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    5.2
...
```

I used APT to install libhmsbeagle1 and libhmsbeagle-dev. I think this installed version 2.1-2 (according to apt-cache madison) under package name hmsbeagle-2 (according to pkg-config --list-all).

However, MrBayes is not showing a GPU:
```
MrBayes > showbeagle

   Available resources reported by beagle library:
        Resource 0:
        Name: CPU
        Flags: PROCESSOR_CPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE VECTOR_SSE THREADING_NONE

   BEAGLE vesion: 2.1
```

**Comment by msuchard** [comment]
Hi Jeff,

I don't immediately remember if MrBayes attempts to load the BEAGLE *.so files from /usr/local/lib before defaulting to an older version pre-packaged within MrBayes.    I suggest that you first try to compile BEAGLE from source (master branch) and try some the BEAGLE examples.  I'll be able to debug these issues much easier than trying to guess if the issue is inside BEAGLE or MrBayes,

**Comment by msuchard** [comment]
Closing due to lack of response.
